notifications:
  webhooks:
    - https://webhook.commit-email.info/

env:
  global:
    - CC_TEST_REPORTER_ID=7e9fdb9b0066c819e6f0554e4ac81255f4f01d8da2a42ac1152402797e927401
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

matrix:
  include:
    - name: "2.3"
      rvm: 2.3
    - name: "2.4"
      rvm: 2.4.5
    - name: "2.5"
      rvm: 2.5.2
    - name: "2.6"
      rvm: 2.6
    - name: "trunk"
      rvm: ruby-head
    - name: "scanner"
      rvm: 2.6
      env:
        - CSV_PARSER_SCANNER_TEST=yes
    - name: "benchmark"
      rvm: 2.6
      script:
        - bundle exec rake benchmark
    - name: "gem"
      rvm: 2.6
      install:
        - rake install
        - gem install simplecov
      script:
        - mkdir -p tmp
        - cd tmp
        - cp -a ../test/ ./
        - ../run-test.rb
