version: "{build}"
clone_depth: 10

notifications:
  - provider: Webhook
    url: https://webhook.commit-email.info/

environment:
  matrix:
    - RUBY_VERSION: "23"
    - RUBY_VERSION: "23-x64"
    - RUBY_VERSION: "24"
    - RUBY_VERSION: "24-x64"
    - RUBY_VERSION: "25"
    - RUBY_VERSION: "25-x64"
    - RUBY_VERSION: "26"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - RUBY_VERSION: "26-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - RUBY_VERSION: "26-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CSV_PARSER_SCANNER_TEST: "yes"

install:
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby -v
  - bundle install

build: off

test_script:
  - bundle exec rake
